# 기본 설정
server:
  address: 0.0.0.0    # 모든 접속 허용
  port: 8080
#  address: localhost

spring:
  profiles:
    default: dev
    active: dev           # 메인으로 사용할 설정

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.naver.com          # 네이버 SMTP 호스트 주소
    port: 465                     # 네이버 SMTP 포트
    username: ${email-address}
    password: ${email-pw}
    properties:
      mail.smtp.auth: true        # SMTP 서버와의 인증
      mail.smtp.ssl.enable: true  # SSL 보안연결(필수)

springdoc:
#  packages-to-scan: NestNet.NestNetWebSite.NestNet-WebSite
#  packages-to-scan: NestNet.NestNetWebSite.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: false
    display-request-duration: true
    operations-sorter: method

jwt:
  header: Authorization
  secret : ${secret-key}
  access-exp-time: 10000    # 2시간 7200000
  refresh-exp-time: 1209600000    # 14일


logging:
  level:
    org.hibernate.SQL: debug    # 하이버네이트가 생성하는 sql 로그로 출력
    org.hibernate.orm.jdbc.bind: trace    # 쿼리 파라미터 로그 남김
