# 기본 설정
server:
  #  address: 0.0.0.0    # 모든 접속 허용
  port: 8080
  address: localhost

spring:
  profiles:
    default: dev
    active: dev           # 메인으로 사용할 설정

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json


jwt:
  header: Authorization
  secret : ${secret-key}
  access-exp-time: 7200000    # 2시간 7200000
  refresh-exp-time: 1209600000    # 14일


logging:
  level:
    org.hibernate.SQL: debug    # 하이버네이트가 생성하는 sql 로그로 출력
    org.hibernate.orm.jdbc.bind: trace    # 쿼리 파라미터 로그 남김
