# 실제 운영에서의 설정
spring:
  config:
    name: application-prod
    activate:
      on-profile: prod
    location: classpath:/application-prod.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring-datasource-url}
    username: root
    password: ${mysql-pw}

  data:
    redis:
      host: ${redis-host}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true                                    # sout으로 보기에 편안한 sql 출력
        dialect: org.hibernate.dialect.MySQL8Dialect        # mysql 방언
    open-in-view: false

#filePath: C:\nestnetFile\
filePath: ${file-path}
