# 기본 설정
server:
  address: 0.0.0.0              # 모든 접속 허용
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.naver.com          # 네이버 SMTP 호스트 주소
    port: 465                     # 네이버 SMTP 포트
    username: ${email-address}
    password: ${email-pw}
    properties:
      mail.smtp.auth: true        # SMTP 서버와의 인증
      mail.smtp.ssl.enable: true  # SSL 보안연결(필수)

jwt:
  header: Authorization
  secret : ${secret-key}
  access-exp-time: 7200000    # 2시간 7200000
  refresh-exp-time: 1209600000    # 14일

mail-secret-string : ${mail-secret-string}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true

logging:
  level:
    org.hibernate.SQL: debug    # 하이버네이트가 생성하는 sql 로그로 출력
    org.hibernate.orm.jdbc.bind: debug    # 쿼리 파라미터 로그 남김

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: local
    default: local